# Generated by Django 3.1.2 on 2020-10-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201031_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gok_id',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
