# Generated by Django 3.1.2 on 2020-11-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
