# Generated by Django 3.1.2 on 2020-11-01 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0002_neighbourhood_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='count',
        ),
    ]
