# Generated by Django 3.1.2 on 2020-11-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0003_remove_neighbourhood_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='occupants',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
