# Generated by Django 3.1.2 on 2020-11-01 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighbour', '0005_auto_20201101_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('business_type', models.CharField(choices=[('PLUMBER', 'Plumber'), ('HAIR_SALON', 'Hair_Salon'), ('SHOP', 'Shop'), ('GYM', 'Gym'), ('GROCERY', 'Grocery'), ('CAPENTER', 'Capenter'), ('BUTCHERY', 'Butchery'), ('ELECTRICIAN', 'Electrician')], default='Business', max_length=255)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbour.neighbourhood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
